services/arlington/arlington/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('web.urls')),
    path('admin/', admin.site.urls),
]

services/arlington/groups/urls.py
from django.urls import path, include

from groups import views

urlpatterns = [
    path('create', views.GroupCreateView.as_view(), name='group_create'),
    path('', views.GroupListView.as_view(), name='group_list'),
    path('join/<slug:code>/', views.GroupJoinView.as_view(), name='group_join'),
    path('<int:group_id>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('<int:group_id>/', include('groups.document_urls')),
    path('about', views.GroupAbout.as_view(), name='group_about')
]

services/arlington/web/urls.py
from django.urls import path, include

from web import draft_views, views, auth_views

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('home', views.HomeView.as_view()),
    path('auth/register', auth_views.RegisterView.as_view(), name='register'),
    path('auth/login', auth_views.LoginView.as_view(), name='login'),
    path('auth/logout', auth_views.logout_view, name='logout'),
    path('drafts/create', draft_views.DraftCreate.as_view(), name='draft_create'),
    path('drafts/', draft_views.DraftList.as_view(), name='draft_list'),
    path('drafts_about', draft_views.DraftAbout.as_view(), name='draft_about'),
    path('groups/', include(('groups.urls', 'groups'), namespace='groups'))
]

services/arlington/groups/models.py
from django.conf import settings
from django.contrib.auth.models import Group
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class InviteCode(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    code = models.CharField(max_length=16)


class Document(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    rendered_file = models.FileField(upload_to='rendered_docs/', null=True)
    owner = models.ForeignKey(Group, on_delete=models.CASCADE)

    def to_elastic(self):
        return {"text": self.text, "title": self.title, "group_id": self.owner_id, "id": self.id}

services/arlington/web/models.py
from django.contrib.auth.models import Group, User
from django.db import models


class Draft(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

services/arlington/groups/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import redirect
from django.views.generic import CreateView, ListView, DetailView, TemplateView
from django.views import View
from django.contrib.auth.models import Group
from django.urls import reverse

from groups.models import InviteCode
from libs.helpers import optional
from libs.mixins import MembershipRequiredMixin
from libs.cache import cache_decorator


@cache_decorator(lambda code: "invite_" + code, timeout=60 * 5)
def get_group_id_by_code(code):
    return optional(InviteCode.objects.filter(code=code).first()).group_id


class BaseGroupView(LoginRequiredMixin, MembershipRequiredMixin):
    def get_group(self) -> Group:
        return Group.objects.get(id=self.group_id)


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    fields = ["name"]
    template_name = "create.html"

    def form_valid(self, form):
        group = form.save()
        user = self.request.user
        user.groups.add(group)
        code = InviteCode(group=group, code=secrets.token_urlsafe(16))
        code.save()
        return redirect(reverse('groups:group_detail', args=[group.id]))


class GroupListView(LoginRequiredMixin, ListView):
    template_name = "list.html"
    context_object_name = 'groups'

    def get_queryset(self):
        queryset = self.request.user.groups.all().prefetch_related('user_set')
        return queryset


class GroupDetailView(BaseGroupView, DetailView):
    pk_url_kwarg = 'group_id'
    template_name = 'detail.html'
    model = Group

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group = context['group']
        invite_code = optional(InviteCode.objects.filter(group_id=group.id).first()).code
        context['invite_code'] = invite_code
        return context


class GroupJoinView(LoginRequiredMixin, View):
    def get(self, request, code):
        group_id = get_group_id_by_code(code)
        if group_id:
            group = Group.objects.get(id=group_id)
            request.user.groups.add(group)
            return redirect(reverse('groups:group_list'))
        return HttpResponseNotFound("Group not found")


class GroupSearchView(BaseGroupView, TemplateView):
    template_name = "search.html"

    def get_context_data(self, **kwargs):
        return dict()


class GroupAbout(TemplateView):
    template_name = "about.html"

services/arlington/web/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView

from web.models import Draft


class IndexView(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/home')
        return super().get(request, *args, **kwargs)


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        last_draft = Draft.objects.filter(owner=self.request.user).order_by('-id').first()
        drafts_count = Draft.objects.filter(owner=self.request.user).count()

        groups = self.request.user.groups.all()

        last_draft_text_short = last_draft.text if last_draft is not None else ""
        last_draft_text_short = last_draft_text_short if len(last_draft_text_short) < 30 else last_draft_text_short[:20] + "..."

        return {
            'last_draft': last_draft,
            'last_draft_text_short': last_draft_text_short,
            'drafts_count': drafts_count,
            'groups_count': len(groups),
            'last_group': groups[len(groups) - 1] if len(groups) > 0 else None
        }

services/arlington/groups/templates/about.html
{% extends "base.html" %}

{% block main %}

    {% if message %}
        <p class='bg-danger rounded p-2'>{{ message }}</p>
    {% endif %}


    <h3 style="color: white">HELP / Groups</h3>
    <h5><a href="/">&larr; back home</a></h5>

    <p style="color: white">
        Group is a main way to unite knowledge after the Great Boom. <br />
        You can create documents and share them within group.
        You can only see documents in the group if you are a part of it!
    </p>
{% endblock %}

services/arlington/groups/templates/create.html
{% extends "base.html" %}

{% block main %}

{% if form.errors %}
    <p style="color: white" class='bg-danger rounded p-2'>Error</p>
        <label style="color: white">
        {% for k,v in form.errors.items %}
            <p>{{ k }} : {{ v }}</p>
        {% endfor %}
{% endif %}

<h3>Create new group</h3>
<form action='' method='post'>
    {% csrf_token %}
    {% for row in form %}
        <label style="color: white">
            Group name:
            {{ row }}
        </label>
    {% endfor %}
    <input type='submit' value='Create' class='button'>
</form>

{% endblock %}

services/arlington/groups/templates/detail.html
{% extends "base.html" %}

{% block main %}
    <h3>Brotherhood {{ object.name }} (users: {{ object.user_set.count }} pcs) welcomes you!</h3>
    <h5 style="color: white">Invite code: {{ invite_code }}</h5>

    <div class="grid-x">
        <div class="columns small-6">
            <div class="card">
                <div class="card-section">
                    <ul class="menu">
                        <li><a href="{% url 'groups:document_create' object.id %}"><span>Create new document</span></a>
                        </li>
                        <li><a href="{% url 'groups:documents_list' object.id %}"><span>List documents</span></a></li>
                    </ul>

                    <form id="search-form">
                        <div class="input-group" style="margin-bottom: 0; margin-top: 1em;">
                            <input class="input-group-field" type="text" placeholder="Taxes report..." id="search-value">
                            <div class="input-group-button">
                                <input type="submit" class="button" value="Search document">
                            </div>
                        </div>
                    </form>
                    <script>
                        $(document).ready(function() {
                            $("#search-form").on("submit", function() {
                                var val = $("#search-value").val();
                                window.location.replace("/groups/{{ object.id }}/documents/search?q=" + val);
                                return false;
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

services/arlington/groups/templates/documents/create.html
{% extends "base.html" %}

{% block main %}

{% if message %}
    <p class='bg-danger rounded p-2'>{{ message }}</p>
{% endif %}

<h3>Create document</h3>
    <h5><a href="#" onclick="window.history.go(-1); return false">&larr; back </a></h5>

<form action='' method='post'>
    {% csrf_token %}
    {% for row in form %}
        <label style="color: white;">
            {% if row.name == "title" %}
                Name of the document:
            {% else %}
                Document contents:
            {% endif %}
        {{ row }}
        </label>
    {% endfor %}
    <input type='submit' value='Create document' class='button'>
</form>

{% endblock %}

services/arlington/groups/templates/documents/detail.html
{% extends "base.html" %}

{% block main %}

    {% if message %}
        <p class='bg-danger rounded p-2'>{{ message }}</p>
    {% endif %}


    <div class='card'>
        <div class="card-divider">
            <h4>{{ object.title|truncatechars:140 }}</h4>
        </div>
        <div class='card-section'>
            <pre>{{ object.text }}</pre>

            {% if object.rendered_file == '' %}
                <p>Render temporary unavailable</p>
            {% else %}
                <p>Get the <a href="/{{ object.rendered_file }}">render</a></p>
            {% endif %}
        </div>
    </div>


{% endblock %}

services/arlington/groups/templates/documents/list.html
{% extends "base.html" %}

{% block main %}
    {% if message %}
        <p class='bg-danger rounded p-2'>{{ message }}</p>
    {% endif %}


    {% for doc in docs %}
        {% if forloop.first %}
            <div class='row'>
                {% else %}
                {% if forloop.counter0|divisibleby:"4" %}
                    </div>
                    <div class='row'>
                {% endif %}
        {% endif %}

    <div class='card'>
        <div class="card-divider">
            <h4>{{ doc.title|truncatechars:140 }}</h4>
        </div>
        <div class='card-section'>
            <pre>{{ doc.text }}</pre>

            {% if doc.rendered_file == '' %}
                <p>Render temporary unavailable</p>
            {% else %}
                <p>Get the <a href="/{{ doc.rendered_file }}">render</a></p>
            {% endif %}
        </div>
    </div>

    {% if forloop.last %}
        </div>
    {% endif %}
        {% empty %}
        <h3>No documents yet!</h3>
    {% endfor %}
    <h5><a onclick="window.history.go(-1)">&larr; go back</a></h5>

{% endblock %}

services/arlington/groups/templates/documents/search_result.html
{% extends "base.html" %}

{% block main %}
    {% if message %}
        <p class='bg-danger rounded p-2'>{{ message }}</p>
    {% endif %}

    {% for doc in docs %}
        {% if forloop.first %}
            <div class='row'>
                {% else %}
                {% if forloop.counter0|divisibleby:"4" %}
                    </div>
                    <div class='row'>
                {% endif %}
        {% endif %}

    <div class='card'>
        <div class="card-divider">
            <h4>{{ doc.title|truncatechars:140 }}</h4>
        </div>
        <div class='card-section'>
            <pre>{{ doc.text }}</pre>
        </div>
    </div>

    {% if forloop.last %}
        </div>
    {% endif %}
    {% empty %}
        <h3>Sorry! No result =c</h3>
    {% endfor %}
    <h5><a onclick="window.history.go(-1)">&larr; go back</a></h5>

{% endblock %}

services/arlington/groups/templates/list.html
{% extends "base.html" %}

{% block main %}

    {% if message %}
        <p class='bg-danger rounded p-2'>{{ message }}</p>
    {% endif %}

    {% for group in groups %}
        {% if forloop.first %}
            <div class='row'>
                {% else %}
                {% if forloop.counter0|divisibleby:"4" %}
                    </div>
                    <div class='row'>
                {% endif %}
        {% endif %}

    <div class='card'>
        <div class="card-divider">
            <h4> {{ group.name|truncatechars:140 }}</h4>
        </div>
        <div class='card-section'>
            <p>Users in group: <b>{{ group.user_set.count }}</b></p>
            <p><a href="{% url 'groups:group_detail' group.id %}">Details</a></p>
        </div>
    </div>

    {% if forloop.last %}
        </div>
    {% endif %}
    {% empty %}
        <h3>No groups now... <a href="{% url "groups:group_create" %}">Create new!</a></h3>
        <h5><a href="/">&larr; to main page</a></h5>
    {% endfor %}

{% endblock %}

services/arlington/web/templates/base.html
{% load staticfiles %}

<!doctype html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Arlington | Knowledge base</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.0/dist/css/foundation.min.css"
          integrity="sha256-VEEaOnBKVRoYPn4AID/tY/XKVxKEqXstoo/xZ6nemak= sha384-D46t32f421/hB30qwnim2pIcisNN5GU9+6m2Mfnd3dKpTSFidZLa08/1StEiCFId sha512-WkgzH8VKemDfwrp18r+wgbx+oHXOkfd2kJs7ocAXdGDgonXDXh88E90IRtRZRXtO0IHprxYHYlY14h+wyTsUDA=="
          crossorigin="anonymous">
    <link rel="icon" href="/static/logo.ico">
    <link rel="stylesheet" href="/static/css/footer.css">
    <link rel="stylesheet" href="/static/css/login-form.css">

    <style type="text/css">
        /* Fuck everyone */

        html {
            min-width: 1300px;
            padding: 0;
            margin: 0;
            width: 100%;
            height: 100%;
        }

        body {
            background: url("/static/connectwork.png");
            min-width: 1300px;
            padding: 0;
            margin: 0;
            width: 100%;
            height: 100%;
        }

        h1, h2, h3 {
            color: white;
        }
    </style>

</head>
<body>
<header>
    <div class="top-bar">
        <div class="top-bar-left">
            <ul class="dropdown menu" data-dropdown-menu>
                <li class="menu-text" style="color: black; cursor: pointer;" onclick="window.location='/';">
                    <span>Arlington</span>
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <a href="/home">Home</a>
                    </li>
                    <li>
                        <a href="{% url "draft_list" %}">Drafts</a>
                    </li>
                    <li>
                        <a href="{% url 'groups:group_list' %}">Groups</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <div class="top-bar-right">
            <ul class="menu">
                {% if user.is_authenticated %}
                    <li class='nav-item'>
                        <a class='nav-link' href='{% url "logout" %}'>Logout ({{ user.username }},
                            id: {{ user.id }})</a>
                    </li>
                {% else %}
                    <li class='nav-item'>
                        <a class='nav-link' href='{% url "login" %}'>Login</a>
                    </li>
                    <li class='nav-item'>
                        <a class='nav-link' href='{% url "register" %}'>Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>

<div style="padding: 30px; margin: 0;">
    {% block main %}{% endblock %}
</div>

<div id="footer">
    <div class="grid-x" style="width: 100%;">
        <div class="cell small-9">
            <p style="font-size: 1.1em; word-break: keep-all; white-space: nowrap;">
                Powered by VaultServants. Send claims to <b>/dev/null</b>.
            </p>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.0/dist/js/foundation.min.js"
        integrity="sha256-GZq6aeugpWo25iH//1eKmeK6FHCf+6KXTfoUpkCqPCA= sha384-vjxUQtbGw5FJMigaaFpXYyxoHHLb7LbvRywnMZOiPJeh5j9sl2rnmQ3iucuegRm8 sha512-h7tIMIX/opZXfWkcTDbkO+nT0LePyAAwDacfYhWtgGUidV+Kkh3eesW52fPSxKEsw3rgywKhQvghNLT4eDuUyw=="
        crossorigin="anonymous"></script>
<script type="text/javascript">
    $(document).foundation();
</script>
</body>
</html>

services/arlington/web/templates/draft/about.html
{% extends "base.html" %}

{% block main %}

    {% if message %}
        <p class='bg-danger rounded p-2'>{{ message }}</p>
    {% endif %}


    <h3 style="color: white">HELP / Personal drafts</h3>
    <h5><a href="/">&larr; back home</a></h5>

    <p style="color: white">
        Personal drafts are <b>secret</b> and unavailable to other users. <br />
        You can use them as a storage for your secret data. We will never share it to anyone.
        You don't have any limit on a count of your personal drafts. Have a good day!
    </p>
{% endblock %}

services/arlington/web/templates/draft/create.html
{% extends "base.html" %}

{% block main %}

{% if message %}
    <p class='bg-danger rounded p-2'>{{ message }}</p>
{% endif %}

<h3>Create draft </h3>
    <h5><a href="#" onclick="window.history.go(-1); return false">&larr; back </a></h5>

<form action='' method='post'>
    {% csrf_token %}
    {% for row in form %}
        <label style="color: white;">
            {% if row.name == "title" %}
                Name of the draft:
            {% else %}
                Draft contents:
            {% endif %}
        {{ row }}
        </label>
    {% endfor %}
    <input type='submit' value='Create draft' class='button'>
</form>

{% endblock %}

services/arlington/web/templates/draft/list.html
{% extends "base.html" %}

{% block main %}

    {% if message %}
        <p class='bg-danger rounded p-2'>{{ message }}</p>
    {% endif %}

    {% for draft in drafts %}
        {% if forloop.first %}
            <div class='row'>
                {% else %}
                {% if forloop.counter0|divisibleby:"4" %}
                    </div>
                    <div class='row'>
                {% endif %}
        {% endif %}

    <div class='card'>
        <div class="card-divider">
            <h4>{{ draft.title|truncatechars:140 }}</h4>
        </div>
        <div class='card-section'>
            <p>{{ draft.text }}</p>
        </div>
    </div>

    {% if forloop.last %}
        </div>
    {% endif %}
    {% empty %}
        <h3>No notes now... <a href="{% url "draft_create" %}">Create new!</a></h3>
        <h5><a href="/">&larr; to main page</a></h5>
    {% endfor %}

{% endblock %}

services/arlington/web/templates/home.html
{% extends "base.html" %}

{% block main %}
    <h2>
        <img src="/static/logo_white.svg" width="64" height="64"/>
        Welcome home!
    </h2>
    <br>

    <div class="grid-x">
        <div class="cell small-4">
            <div class="card" style="width: 400px;">
                <div class="card-divider" style="color: black;">
                    Your personal drafts ({{ drafts_count }} pcs)
                </div>
                <div class="card-section">
                    {#                    <h4>Or <a href="{% url "draft_list" %}">see</a> created</h4>#}
                    {% if drafts_count > 0 %}
                        <span>Last draft:
                            <b>{{ last_draft.title }}</b> &mdash; {{ last_draft_text_short }}
                        </span>
                    {% else %}
                        <hspan>You don't have drafts yet</hspan>
                    {% endif %}
                    <ul class="menu">
                        <li><a href="{% url "draft_create" %}"><span>Create new</span></a></li>
                        <li><a href="{% url "draft_list" %}"><span>List all</span></a></li>
                        <li><a href="{% url "draft_about" %}"><span>What is it?</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="cell small-4">
            <div class="card" style="width: 400px;">
                <div class="card-divider" style="color: black;">
                    Your groups ({{ groups_count }} pcs)
                </div>
                <div class="card-section">
                    {#                    <h4>Or <a href="{% url "draft_list" %}">see</a> created</h4>#}
                    {% if groups_count > 0 %}
                        <span>Last group:
                            <a href="/groups/{{ last_group.id }}"><b>{{ last_group.name }}</b></a>
                        </span>
                    {% else %}
                        <span>You don't have groups yet</span>
                    {% endif %}
                    <ul class="menu">
                        <li><a href="{% url "groups:group_create" %}"><span>Create new</span></a></li>
                        <li><a href="{% url "groups:group_list" %}"><span>List my groups</span></a></li>
                        <li><a href="{% url "groups:group_about" %}"><span>What is it?</span></a></li>
                    </ul>
                    <form id="join-group-form">
                        <div class="input-group" style="margin-bottom: 0;">
                            <input class="input-group-field" type="text" placeholder="Invide code" id="join-group-code">
                            <div class="input-group-button">
                                <input type="submit" class="button" value="Join group" id="join-group-button">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
           $("#join-group-form").on("submit", function() {
                var code = $("#join-group-code").val();
                window.location.replace("/groups/join/" + code + "/");
                return false;
           });
        });
    </script>
{% endblock %}

services/arlington/web/templates/index.html
{% extends "base.html" %}

{% block main %}
    <h2>
        <img src="/static/logo_white.svg" width="64" height="64"/>
        United knowledge. Unlimited power.
    </h2>
    <br>

    <div class="grid-x">
        <div class="cell small-3">
            <div class="card" style="width: 300px;">
                <div class="card-divider" style="color: black;">
                    Don't hide your drafts &mdash;
                </div>
                <div class="card-section">
                    <h4>Share them.</h4>
                    <p>Let other members of aftershock society make an impact towards your ideas!</p>
                </div>
            </div>
        </div>
        <div class="cell small-3">
            <div class="card" style="width: 300px;">
                <div class="card-divider" style="color: black;">
                    Don't stay alone &mdash;
                </div>
                <div class="card-section">
                    <h4>Work together.</h4>
                    <p>Together, we can build a strong future for our knowledge, as strong as we want!</p>
                </div>
            </div>
        </div>
        <div class="cell small-6">
            <div class="grid-x">
                <div class="cell small-6 small-offset-3">
                    <div class="translucent-form-overlay">
                        <form action="/auth/login?next=/home" method="post">
                            {% csrf_token %}
                            <h3>Welcome back</h3>
                            <div class="row columns">
                                <label>Login
                                    <input type="text" name="username" placeholder="Avaultunto">
                                </label>
                            </div>
                            <div class="row columns">
                                <label>Password
                                    <input type="password" name="password" placeholder="*******">
                                </label>
                            </div>
                            <div class="row">
                                <label class="columns small-12">First time?
                                    <a href="/auth/register" style="color: #a9d1dd;">Sign up</a>
                                </label>
                            </div>
                            <input type="submit" class="primary button expanded search-button" value="Sign in">
                            {#                                Sign in#}
                            {#                            </button>#}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}